package pipeline

import (
	"fmt"
	"strings"

	"github.com/testifysec/hardener/internal/policy"
	"github.com/testifysec/hardener/internal/profile"
	"github.com/testifysec/hardener/internal/vm"
)

// buildRPM packages the compiled .pp as <app>-selinux RPM inside the VM and
// returns the built RPM path (inside the VM). The .fc it ships is the one
// installPolicy wrote, which already omits base-policy collisions.
func buildRPM(r vm.Runner, p *profile.Profile, revision string) (string, error) {
	app := policy.SafeName(p.Name)
	spec := GenerateSpec(p, revision)
	if err := r.WriteFile(fmt.Sprintf("/tmp/hardener/%s/%s-selinux.spec", app, app), spec); err != nil {
		return "", err
	}
	script := fmt.Sprintf(`set -e
mkdir -p ~/rpmbuild/{SOURCES,SPECS}
cp /tmp/hardener/%[1]s/%[1]s.pp ~/rpmbuild/SOURCES/
cp /tmp/hardener/%[1]s/%[1]s.fc ~/rpmbuild/SOURCES/
cp /tmp/hardener/%[1]s/%[1]s-selinux.spec ~/rpmbuild/SPECS/
rpmbuild -bb ~/rpmbuild/SPECS/%[1]s-selinux.spec
ls ~/rpmbuild/RPMS/noarch/%[1]s-selinux-*.rpm
`, app)
	out, err := r.Run(script)
	if err != nil {
		return "", err
	}
	lines := strings.Split(strings.TrimSpace(out), "\n")
	return lines[len(lines)-1], nil
}

// GenerateSpec renders the RPM spec for the policy package. revision is a
// monotonically increasing build stamp (e.g. a UTC timestamp) that becomes part
// of the Release: two policy builds with different content must not share a
// NEVRA, or an `rpm -U` could keep the old confinement while a new verdict
// describes different bytes (review finding).
func GenerateSpec(p *profile.Profile, revision string) string {
	app := policy.SafeName(p.Name)
	execType := policy.TypeForKind(p.Name, policy.KindExec)
	if revision == "" {
		revision = "0"
	}
	var relabel strings.Builder
	for _, root := range RelabelRoots(p) {
		fmt.Fprintf(&relabel, "restorecon -RF -- %s 2>/dev/null || :\n", vm.ShellQuote(root))
	}
	// The entrypoint label is load-bearing: without _exec_t the domain
	// transition never fires and the service runs unconfined. Relabel it, FAIL
	// if restorecon errors, and then VERIFY the resulting type is actually
	// <app>_exec_t — restorecon also "succeeds" when a higher-priority local
	// file-context rule applies a different type, which would silently leave the
	// service unconfined (review finding). Paths are single-quoted so a manifest
	// path can never inject shell into the customer's %post.
	for _, exe := range p.Executables {
		q := vm.ShellQuote(exe)
		fmt.Fprintf(&relabel,
			"restorecon -F -- %[1]s || { echo \"ERROR: cannot label entrypoint %[2]s; the service would run unconfined\" >&2; exit 1; }\n"+
				"_lbl=$(stat -c '%%C' -- %[1]s 2>/dev/null); case \"$_lbl\" in *:%[3]s:*) : ;; *) echo \"ERROR: entrypoint %[2]s is labeled '$_lbl', not %[3]s — a higher-priority file-context rule is overriding it; the service would run unconfined\" >&2; exit 1 ;; esac\n",
			q, exe, execType)
	}
	var ports strings.Builder
	var portsDel strings.Builder
	for _, port := range p.Ports {
		fmt.Fprintf(&ports, "semanage port -a -t %s -p %s %d 2>/dev/null || :\n",
			policy.PortType(p.Name), port.Proto, port.Port)
		fmt.Fprintf(&portsDel, "    semanage port -d -t %s -p %s %d 2>/dev/null || :\n",
			policy.PortType(p.Name), port.Proto, port.Port)
	}
	return fmt.Sprintf(`Name:           %[1]s-selinux
Version:        1.0.0
Release:        1.%[5]s%%{?dist}
Summary:        SELinux confinement policy for %[1]s (generated by hardener)
License:        Apache-2.0
BuildArch:      noarch
Source0:        %[1]s.pp
Source1:        %[1]s.fc
Requires:       policycoreutils
Requires(post): policycoreutils policycoreutils-python-utils
Requires(postun): policycoreutils

%%description
Machine-generated least-privilege SELinux policy module confining %[1]s.
Produced by the hardener pipeline from static analysis plus observed runtime
behavior, validated against the workload with SELinux Enforcing.

%%install
install -D -m 0644 %%{SOURCE0} %%{buildroot}%%{_datadir}/selinux/packages/%[1]s.pp
install -D -m 0644 %%{SOURCE1} %%{buildroot}%%{_datadir}/selinux/hardener/%[1]s.fc

%%post
# Fail closed: a package that "installs" without loading its policy leaves
# the application unconfined while looking hardened.
if ! semodule -i %%{_datadir}/selinux/packages/%[1]s.pp; then
    echo "ERROR: semodule failed to load the %[1]s policy module; the application is NOT confined" >&2
    exit 1
fi
%[2]s%[3]s
%%postun
if [ $1 -eq 0 ]; then
%[4]s    semodule -r %[1]s 2>/dev/null || :
fi

%%files
%%{_datadir}/selinux/packages/%[1]s.pp
%%{_datadir}/selinux/hardener/%[1]s.fc
`, app, relabel.String(), ports.String(), portsDel.String(), revision)
}
