package pipeline

import (
	"fmt"
	"strings"

	"github.com/testifysec/hardener/internal/policy"
	"github.com/testifysec/hardener/internal/profile"
	"github.com/testifysec/hardener/internal/vm"
)

// buildRPM packages the compiled .pp as <app>-selinux RPM inside the VM and
// returns the built RPM path (inside the VM). The .fc it ships is the one
// installPolicy wrote, which already omits base-policy collisions.
func buildRPM(r vm.Runner, p *profile.Profile) (string, error) {
	app := policy.SafeName(p.Name)
	spec := GenerateSpec(p)
	if err := r.WriteFile(fmt.Sprintf("/tmp/hardener/%s/%s-selinux.spec", app, app), spec); err != nil {
		return "", err
	}
	script := fmt.Sprintf(`set -e
mkdir -p ~/rpmbuild/{SOURCES,SPECS}
cp /tmp/hardener/%[1]s/%[1]s.pp ~/rpmbuild/SOURCES/
cp /tmp/hardener/%[1]s/%[1]s.fc ~/rpmbuild/SOURCES/
cp /tmp/hardener/%[1]s/%[1]s-selinux.spec ~/rpmbuild/SPECS/
rpmbuild -bb ~/rpmbuild/SPECS/%[1]s-selinux.spec
ls ~/rpmbuild/RPMS/noarch/%[1]s-selinux-*.rpm
`, app)
	out, err := r.Run(script)
	if err != nil {
		return "", err
	}
	lines := strings.Split(strings.TrimSpace(out), "\n")
	return lines[len(lines)-1], nil
}

// GenerateSpec renders the RPM spec for the policy package.
func GenerateSpec(p *profile.Profile) string {
	app := policy.SafeName(p.Name)
	var relabel strings.Builder
	for _, root := range RelabelRoots(p) {
		fmt.Fprintf(&relabel, "restorecon -RF %q 2>/dev/null || :\n", root)
	}
	// The entrypoint label is load-bearing: without _exec_t the domain
	// transition never fires and the service runs unconfined. Relabel it
	// explicitly and FAIL the scriptlet if the label cannot be applied —
	// unlike the best-effort relabels above (review finding).
	for _, exe := range p.Executables {
		fmt.Fprintf(&relabel, "restorecon -F %q || { echo \"ERROR: cannot label entrypoint %s; the service would run unconfined\" >&2; exit 1; }\n", exe, exe)
	}
	var ports strings.Builder
	var portsDel strings.Builder
	for _, port := range p.Ports {
		fmt.Fprintf(&ports, "semanage port -a -t %s -p %s %d 2>/dev/null || :\n",
			policy.PortType(p.Name), port.Proto, port.Port)
		fmt.Fprintf(&portsDel, "    semanage port -d -t %s -p %s %d 2>/dev/null || :\n",
			policy.PortType(p.Name), port.Proto, port.Port)
	}
	return fmt.Sprintf(`Name:           %[1]s-selinux
Version:        1.0.0
Release:        1%%{?dist}
Summary:        SELinux confinement policy for %[1]s (generated by hardener)
License:        Apache-2.0
BuildArch:      noarch
Source0:        %[1]s.pp
Source1:        %[1]s.fc
Requires:       policycoreutils
Requires(post): policycoreutils policycoreutils-python-utils
Requires(postun): policycoreutils

%%description
Machine-generated least-privilege SELinux policy module confining %[1]s.
Produced by the hardener pipeline from static analysis plus observed runtime
behavior, validated against the workload with SELinux Enforcing.

%%install
install -D -m 0644 %%{SOURCE0} %%{buildroot}%%{_datadir}/selinux/packages/%[1]s.pp
install -D -m 0644 %%{SOURCE1} %%{buildroot}%%{_datadir}/selinux/hardener/%[1]s.fc

%%post
# Fail closed: a package that "installs" without loading its policy leaves
# the application unconfined while looking hardened.
if ! semodule -i %%{_datadir}/selinux/packages/%[1]s.pp; then
    echo "ERROR: semodule failed to load the %[1]s policy module; the application is NOT confined" >&2
    exit 1
fi
%[2]s%[3]s
%%postun
if [ $1 -eq 0 ]; then
%[4]s    semodule -r %[1]s 2>/dev/null || :
fi

%%files
%%{_datadir}/selinux/packages/%[1]s.pp
%%{_datadir}/selinux/hardener/%[1]s.fc
`, app, relabel.String(), ports.String(), portsDel.String())
}
